name: Bot Loker Otomatis

on:
  schedule:
    # 02.00 UTC = 09.00 WIB, 05.00 UTC = 12.00 WIB, 11.00 UTC = 18.00 WIB
    - cron: '0 2,5,11 * * *'
  workflow_dispatch:

jobs:
  jalankan-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil kode
        uses: actions/checkout@v3

      - name: Siapkan Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Paket
        run: |
          pip install requests google-genai

      - name: Jalankan Script Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FONNTE_TOKEN: ${{ secrets.FONNTE_TOKEN }}
        run: python bot_loker.py
